export const APP_ACTIONS = {
  BillingPage: "BillingPage",
  EditClientBasicInfo: "EditClientBasicInfo",
  EditClientMedicalInfo: "EditClientMedicalInfo",
  EditClientNotes: "EditClientNotes",
  DeleteDocs: "DeleteDocs",
  AddDocs: "AddDocs",
  AddClient: "AddClient",
  AccessControl: "AccessControl",
  ClientAppointmentInfoEdit: "ClientAppointmentInfoEdit",
  ClientAppointmentAdd: "ClientAppointmentAdd",
  ChangeClientStatus: "ChangeClientStatus",
  EditAgensyForms: "EditAgensyForms",
  ViewPersonalInfo: "ViewPersonalInfo",
  OCRAccess: "OCRAccess",
};
