import type { Template } from "@agensy/types";

export const CLIENTS = [
  {
    id: 1,
    name: "Alice Johnson",
    dob: "1945-06-15",
    living: "Assisted Living",
    status: "Active",
    lastUpdated: "2024-07-10T12:00:00.000Z",
  },
  {
    id: 2,
    name: "Robert Smith",
    dob: "1938-03-22",
    living: "Home Care",
    status: "Active",
    lastUpdated: "2025-02-09T12:00:00.000Z",
  },
  {
    id: 3,
    name: "Emma Davis",
    dob: "1942-11-04",
    living: "Nursing Home",
    status: "Inactive",
    lastUpdated: "2022-07-07T12:00:00.000Z",
  },
  {
    id: 4,
    name: "William Brown",
    dob: "1950-07-30",
    living: "Independent Living",
    status: "Active",
    lastUpdated: "2023-07-06T12:00:00.000Z",
  },
  {
    id: 5,
    name: "Margaret Wilson",
    dob: "1947-04-12",
    living: "Assisted Living",
    status: "Active",
    lastUpdated: "2023-07-05T12:00:00.000Z",
  },
  {
    id: 6,
    name: "William Brown",
    dob: "1950-07-30",
    living: "Independent Living",
    status: "Active",
    lastUpdated: "2023-07-03T12:00:00.000Z",
  },
  {
    id: 7,
    name: "Margaret Wilson",
    dob: "1947-04-12",
    living: "Assisted Living",
    status: "Active",
    lastUpdated: "2023-07-03T12:00:00.000Z",
  },
  {
    id: 8,
    name: "William Brown",
    dob: "1950-07-30",
    living: "Independent Living",
    status: "Active",
    lastUpdated: "2023-06-26T12:00:00.000Z",
  },
  {
    id: 9,
    name: "Margaret Wilson",
    dob: "1947-04-12",
    living: "Assisted Living",
    status: "Active",
    lastUpdated: "2023-06-24T12:00:00.000Z",
  },
];

export const MEDICATIONS = [
  {
    id: 1,
    client_id: 1,
    medication_name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    purpose: "Diabetes",
    prescribing_doctor: "Dr. Johnson",
    refill_due: "2025-05-10",
    active: true,
    start_date: "2025-05-01",
    end_date: "2025-05-10",
  },
  {
    id: 2,
    client_id: 1,
    medication_name: "Metformin",
    dosage: "500mg",
    frequency: "Twice daily",
    purpose: "Diabetes",
    prescribing_doctor: "Dr. Johnson",
    refill_due: "2025-05-10",
    active: true,
    start_date: "2025-05-01",
    end_date: "2025-05-10",
  },
];

export const MOCK_PROVIDER = [
  {
    id: 1,
    client_id: 100,
    provider_type: "physician",
    provider_name: "Dr. Smith",
    specialty: "Neurology",
    address: "456 Brain Ave, Austin, TX 78702",
    phone: "(555) 987-6543",
    fax: "(555) 987-6544",
    last_visit: "2025-04-10",
    next_visit: "2025-07-10",
    notes: null,
    created_at: "2025-01-01T12:00:00Z",
    updated_at: "2025-01-01T12:00:00Z",
  },
  {
    id: 2,
    client_id: 100,
    provider_type: "doctor",
    provider_name: "Dr. Johnson",
    specialty: "Primary Care",
    address: "123 Health Street, Austin, TX 78701",
    phone: "(555) 123-4567",
    fax: "(555) 123-4568",
    last_visit: "2025-03-15",
    next_visit: "2025-06-15",
    notes: "Annual physical scheduled for next visit",
    created_at: "2025-01-01T12:00:00Z",
    updated_at: "2025-01-01T12:00:00Z",
  },
];

export const MOCK_DOCUMENTS = [
  {
    id: 1,
    title: "Lab Results – Blood Work",
    category: "Medical Records",
    uploaded: "Apr 10, 2025",
    type: "PDF",
    size: "1.2 MB",
    by: "John Doe",
  },
  {
    id: 2,
    title: "Power of Attorney",
    category: "Legal Documents",
    uploaded: "Apr 11, 2025",
    type: "PDF",
    size: "2.4 MB",
    by: "John Doe",
  },
];

export const MOCK_CONTACT_ACCESS = [
  {
    id: "1",
    contactName: "Jane Doe",
    relationship: "daughter",
    email: "jane.doe@email.com",
    phone: "(555) 123-4567",
    role: "Family Member" as const,
    assignedDate: "2024-01-15",
    assignedBy: "Dr. Smith",
    notes: "Primary family contact and healthcare proxy",
  },
  {
    id: "2",
    contactName: "Michael Johnson",
    relationship: "son",
    email: "michael.johnson@email.com",
    phone: "(555) 234-5678",
    role: "Family Member" as const,
    assignedDate: "2024-01-20",
    assignedBy: "Admin",
    notes: "Secondary family contact",
  },
  {
    id: "3",
    contactName: "Sarah Williams",
    relationship: "caregiver",
    email: "sarah.williams@careservice.com",
    phone: "(555) 345-6789",
    role: "Caregiver" as const,
    assignedDate: "2024-02-01",
    assignedBy: "Nursing Supervisor",
    notes: "Primary home care provider, certified nursing assistant",
    contact: {
      id: "3",
      client_id: "100",
      contact_type: "emergency" as const,
      first_name: "Sarah",
      last_name: "Williams",
      relationship: "caregiver",
      phone: "(555) 345-6789",
      email: "sarah.williams@careservice.com",
      address: "789 Care Blvd, Austin, TX 78703",
      notes: [],
      active: true as const,
      createdAt: new Date("2024-02-01"),
      updatedAt: new Date("2024-02-01"),
    },
  },
  {
    id: "4",
    contactName: "Robert Martinez",
    relationship: "caregiver",
    email: "robert.martinez@homecare.com",
    phone: "(555) 456-7890",
    role: "Caregiver" as const,
    assignedDate: "2024-02-15",
    assignedBy: "Care Coordinator",
    notes: "Weekend caregiver, specializes in mobility assistance",
    contact: {
      id: "4",
      client_id: "100",
      contact_type: "secondary" as const,
      first_name: "Robert",
      last_name: "Martinez",
      relationship: "caregiver",
      phone: "(555) 456-7890",
      email: "robert.martinez@homecare.com",
      address: "321 Helper St, Austin, TX 78704",
      notes: [],
      active: true as const,
      createdAt: new Date("2024-02-15"),
      updatedAt: new Date("2024-02-15"),
    },
  },
  {
    id: "5",
    contactName: "Emily Davis",
    relationship: "spouse",
    email: "emily.davis@email.com",
    phone: "(555) 567-8901",
    role: "Family Member" as const,
    assignedDate: "2024-01-10",
    assignedBy: "Admin",
    notes: "Spouse, lives with client",
    contact: {
      id: "5",
      client_id: "100",
      contact_type: "primary" as const,
      first_name: "Emily",
      last_name: "Davis",
      relationship: "spouse",
      phone: "(555) 567-8901",
      email: "emily.davis@email.com",
      address: "Same as client",
      notes: [],
      active: true as const,
      createdAt: new Date("2024-01-10"),
      updatedAt: new Date("2024-01-10"),
    },
  },
  {
    id: "6",
    contactName: "Lisa Thompson",
    relationship: "caregiver",
    email: "lisa.thompson@medicalcare.com",
    phone: "(555) 678-9012",
    role: "Caregiver" as const,
    assignedDate: "2024-03-01",
    assignedBy: "Medical Director",
    notes: "Licensed practical nurse, handles medication management",
    contact: {
      id: "6",
      client_id: "100",
      contact_type: "emergency" as const,
      first_name: "Lisa",
      last_name: "Thompson",
      relationship: "caregiver",
      phone: "(555) 678-9012",
      email: "lisa.thompson@medicalcare.com",
      address: "654 Nursing Way, Austin, TX 78705",
      notes: [],
      active: true as const,
      createdAt: new Date("2024-03-01"),
      updatedAt: new Date("2024-03-01"),
    },
  },
  {
    id: "7",
    contactName: "David Brown",
    relationship: "legal_guardian",
    email: "david.brown@legal.com",
    phone: "(555) 789-0123",
    role: "Family Member" as const,
    assignedDate: "2024-01-05",
    assignedBy: "Court Appointment",
    notes: "Legal guardian, manages financial and legal decisions",
    contact: {
      id: "7",
      client_id: "100",
      contact_type: "secondary" as const,
      first_name: "David",
      last_name: "Brown",
      relationship: "legal_guardian",
      phone: "(555) 789-0123",
      email: "david.brown@legal.com",
      address: "987 Legal Plaza, Austin, TX 78706",
      notes: [],
      active: true as const,
      createdAt: new Date("2024-01-05"),
      updatedAt: new Date("2024-01-05"),
    },
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "1",
    title: "Health History Form",
    type: "form",
    description: "Track health history changes over time",
    createdAt: new Date("2025-01-15"),
    completedDate: new Date("2025-02-01"),
  },
  {
    id: "2",
    title: "Medical Appointment",
    type: "form",
    description: "Template for documenting medical appointments",
    createdAt: new Date("2025-01-15"),
  },
  {
    id: "3",
    title: "Hospitalization Checklist",
    type: "checklist",
    description: "Guide for managing hospitalizations",
    createdAt: new Date("2025-01-15"),
    completedDate: new Date("2025-01-20"),
  },
];

export const MOCK_APPOINTMENTS = [
  {
    id: "1",
    appointmentDate: "2025-05-11",
    content: "Lab Work",
    createdAt: new Date("2025-05-01T10:00:00.000Z"),
    updatedAt: new Date("2025-05-01T10:00:00.000Z"),
  },
  {
    id: "2",
    appointmentDate: "2025-05-29",
    content: "Dr. Smith",
    createdAt: new Date("2025-05-02T09:30:00.000Z"),
    updatedAt: new Date("2025-05-02T09:30:00.000Z"),
  },
  {
    id: "3",
    appointmentDate: "2025-05-15",
    content: "Physical Therapy",
    createdAt: new Date("2025-05-03T14:15:00.000Z"),
    updatedAt: new Date("2025-05-03T14:15:00.000Z"),
  },
  {
    id: "4",
    appointmentDate: "2025-05-15",
    content: "Urgent Follow-up",
    createdAt: new Date("2025-05-03T16:45:00.000Z"),
    updatedAt: new Date("2025-05-03T16:45:00.000Z"),
  },
  {
    id: "5",
    appointmentDate: "2025-05-20",
    content: "Regular Checkup",
    createdAt: new Date("2025-05-04T11:20:00.000Z"),
    updatedAt: new Date("2025-05-04T11:20:00.000Z"),
  },
];

export const MOCK_APPOINTMENTS_DATA = [
  {
    id: "550e8400-e29b-41d4-a716-446655440000",
    client_id: "c1b2a3d4-e5f6-4a3b-8c9d-0e1f2a3b4c5d",
    creator: {
      id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
      first_name: "John",
      last_name: "Smith",
      email: "john.smith@example.com",
      cognito_id: "cognito_123",
      active: true,
      email_verified: true,
      last_login: new Date(),
      role: "admin",
    },
    title: "Annual Physical Checkup",
    appointment_type: "Regular Checkup",
    provider_id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6",
    location: "Main Clinic - Room 101",
    start_time: "2024-03-25T09:00:00.000Z",
    end_time: "2024-03-25T10:00:00.000Z",
    all_day: false,
    notes: "Routine annual physical examination",
    reminder_sent: false,
    active: true,
    created_at: "2024-03-20T08:00:00.000Z",
    updated_at: "2024-03-20T08:00:00.000Z",
  },
  {
    id: "660e8400-e29b-41d4-a716-446655440001",
    client_id: "c1b2a3d4-e5f6-4a3b-8c9d-0e1f2a3b4c5d",
    creator: {
      id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
      first_name: "John",
      last_name: "Smith",
      email: "john.smith@example.com",
      cognito_id: "cognito_123",
      active: true,
      email_verified: true,
      last_login: new Date(),
      role: "admin",
    },
    title: "Dental Cleaning",
    appointment_type: "Dental",
    provider_id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6",
    location: "Dental Care Center",
    start_time: "2024-03-26T14:30:00.000Z",
    end_time: "2024-03-26T15:30:00.000Z",
    all_day: false,
    notes: "Regular dental cleaning and checkup",
    reminder_sent: true,
    active: true,
    created_at: "2024-03-21T10:00:00.000Z",
    updated_at: "2024-03-21T10:00:00.000Z",
  },
  {
    id: "770e8400-e29b-41d4-a716-446655440002",
    client_id: "c1b2a3d4-e5f6-4a3b-8c9d-0e1f2a3b4c5d",
    creator: {
      id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
      first_name: "John",
      last_name: "Smith",
      email: "john.smith@example.com",
      cognito_id: "cognito_123",
      active: true,
      email_verified: true,
      last_login: new Date(),
      role: "admin",
    },
    title: "Physical Therapy Session",
    appointment_type: "Therapy",
    provider_id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6",
    location: "Rehabilitation Center",
    start_time: "2024-03-27T11:00:00.000Z",
    end_time: "2024-03-27T12:00:00.000Z",
    all_day: false,
    notes: "Follow-up therapy session for knee rehabilitation",
    reminder_sent: false,
    active: true,
    created_at: "2024-03-22T09:00:00.000Z",
    updated_at: "2024-03-22T09:00:00.000Z",
  },
  {
    id: "880e8400-e29b-41d4-a716-446655440003",
    client_id: "c1b2a3d4-e5f6-4a3b-8c9d-0e1f2a3b4c5d",
    creator: {
      id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
      first_name: "Sarah",
      last_name: "Johnson",
      email: "sarah.johnson@example.com",
      cognito_id: "cognito_456",
      active: true,
      email_verified: true,
      last_login: new Date(),
      role: "staff",
    },
    title: "Lab Work",
    appointment_type: "Laboratory",
    provider_id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6",
    location: "Medical Lab Services",
    start_time: "2024-03-28T08:30:00.000Z",
    end_time: "2024-03-28T09:30:00.000Z",
    all_day: false,
    notes: "Blood work and routine tests",
    reminder_sent: false,
    active: true,
    created_at: "2024-03-23T11:00:00.000Z",
    updated_at: "2024-03-23T11:00:00.000Z",
  },
  {
    id: "990e8400-e29b-41d4-a716-446655440004",
    client_id: "c1b2a3d4-e5f6-4a3b-8c9d-0e1f2a3b4c5d",
    creator: {
      id: "a1b2c3d4-e5f6-7a8b-9c0d-1e2f3a4b5c6d",
      first_name: "Sarah",
      last_name: "Johnson",
      email: "sarah.johnson@example.com",
      cognito_id: "cognito_456",
      active: true,
      email_verified: true,
      last_login: new Date(),
      role: "staff",
    },
    title: "Eye Examination",
    appointment_type: "Vision",
    provider_id: "d1e2f3a4-b5c6-7d8e-9f0a-1b2c3d4e5f6",
    location: "Vision Care Center",
    start_time: "2024-03-29T13:00:00.000Z",
    end_time: "2024-03-29T14:00:00.000Z",
    all_day: false,
    notes: "Annual eye examination and prescription update",
    reminder_sent: false,
    active: true,
    created_at: "2024-03-24T12:00:00.000Z",
    updated_at: "2024-03-24T12:00:00.000Z",
  },
];

// Dashboard dummy data
export const DASHBOARD_DUMMY_USER = {
  id: "1",
  email: "admin@example.com",
  first_name: "Admin",
  last_name: "User",
  role: "admin",
  active: true,
  createdAt: new Date(),
  updatedAt: new Date(),
  cognito_id: "dummy-cognito-id",
  email_verified: true,
  last_login: new Date(),
} as const;

export const DASHBOARD_DUMMY_CLIENTS = [
  {
    id: "1",
    first_name: "John",
    last_name: "Doe",
    phone: "+1234567890",
  },
  {
    id: "2",
    first_name: "Jane",
    last_name: "Smith",
    phone: "+1987654321",
  },
] as const;

export const DASHBOARD_DUMMY_APPOINTMENTS = [
  {
    id: "1",
    title: "Medical Checkup",
    appointment_type: "checkup",
    start_time: "2024-03-20T10:00:00",
    end_time: "2024-03-20T11:00:00",
    location: "Main Clinic",
    client_id: "1",
    healthcare_provider_id: "1",
    active: true,
    createdBy: DASHBOARD_DUMMY_USER,
    provider_id: "1",
    all_day: false,
    notes: "",
    reminder_sent: false,
  },
  {
    id: "2",
    title: "Follow-up",
    appointment_type: "follow_up",
    start_time: "2024-03-21T14:00:00",
    end_time: "2024-03-21T15:00:00",
    location: "Virtual",
    client_id: "2",
    healthcare_provider_id: "2",
    active: true,
    createdBy: DASHBOARD_DUMMY_USER,
    provider_id: "2",
    all_day: false,
    notes: "",
    reminder_sent: false,
  },
] as const;

export const DASHBOARD_DUMMY_MESSAGES = [
  {
    id: "1",
    subject: "New Document Available",
    content: "A new medical report has been uploaded to your profile.",
    sender_id: "1",
    receiver_id: "2",
    read: false,
    priority: "high",
    category: "document",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    subject: "Appointment Reminder",
    content: "Your appointment is scheduled for tomorrow at 2 PM.",
    sender_id: "2",
    receiver_id: "1",
    read: true,
    priority: "medium",
    category: "appointment",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
] as const;

export const DASHBOARD_DUMMY_DOCUMENTS = [
  {
    id: "1",
    title: "Medical Report",
    category: "medical",
    description: "Annual medical examination report",
    document_type: "pdf",
    file_size: 1024,
    file_type: "application/pdf",
    file_url: "https://example.com/doc1.pdf",
    file_name: "medical_report_2024.pdf",
    s3_bucket: "documents",
    client_id: "1",
    active: true,
    upload_type: "client",
    uploadedBy: DASHBOARD_DUMMY_USER,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    title: "Insurance Document",
    category: "insurance",
    description: "Updated insurance policy",
    document_type: "pdf",
    file_size: 2048,
    file_type: "application/pdf",
    file_url: "https://example.com/doc2.pdf",
    file_name: "insurance_2024.pdf",
    s3_bucket: "documents",
    client_id: "2",
    active: true,
    upload_type: "client",
    uploadedBy: DASHBOARD_DUMMY_USER,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
] as const;

export const MOCK_THREADS = [
  {
    id: "1",
    primary_user_id: "1",
    user_id: "2",
    started_at: new Date("2024-03-20T10:00:00Z"),
    last_message: "When can we schedule the next appointment?",
    last_message_time: new Date("2024-03-20T10:30:00Z"),
    last_message_sender_id: "2",
    type: "client",
    subType: "one-to-one",
    created_by: "1",
    messages: [
      {
        id: "1",
        thread_id: "1",
        sender_id: "1",
        content: "Hello, how can I help you today?",
        sent_at: new Date("2024-03-20T10:00:00Z"),
      },
      {
        id: "2",
        thread_id: "1",
        sender_id: "2",
        content: "When can we schedule the next appointment?",
        sent_at: new Date("2024-03-20T10:30:00Z"),
      },
    ],
  },
  {
    id: "2",
    primary_user_id: "1",
    user_id: "3",
    started_at: new Date("2024-03-19T15:00:00Z"),
    last_message: "The documents have been uploaded.",
    last_message_time: new Date("2024-03-19T15:45:00Z"),
    last_message_sender_id: "1",
    type: "general",
    subType: "one-to-one",
    created_by: "1",
    messages: [
      {
        id: "3",
        thread_id: "2",
        sender_id: "3",
        content: "Could you please check the latest medical reports?",
        sent_at: new Date("2024-03-19T15:00:00Z"),
      },
      {
        id: "4",
        thread_id: "2",
        sender_id: "1",
        content: "The documents have been uploaded.",
        sent_at: new Date("2024-03-19T15:45:00Z"),
      },
    ],
  },
] as const;

export const DUMMY_ACTIVITIES = [
  {
    id: "1",
    user_name: "Jane Smith",
    client_name: "Mary Johnson",
    category: "documents" as const,
    action_type: "uploaded",
    description: "Jane Smith uploaded Lab Results",
    timestamp: "2 mins ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    user_name: "System",
    client_name: "Robert Chen",
    category: "appointments" as const,
    action_type: "completed",
    description: "Appointment completed",
    timestamp: "15 mins ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    user_name: "Dr. Lee",
    client_name: "Sarah Williams",
    category: "messages" as const,
    action_type: "sent a message",
    description: "Dr. Lee sent a message",
    timestamp: "30 mins ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    user_name: "Patricia Miller",
    client_name: "Mary Johnson",
    category: "medical" as const,
    action_type: "updated medications",
    description: "Patricia Miller updated medications",
    timestamp: "1 hour ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "5",
    user_name: "Ariel",
    client_name: "Andrea Smith",
    category: "messages" as const,
    action_type: "started a conversation",
    description: "Ariel started a conversation about Andrea Smith",
    timestamp: "2 hours ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "6",
    user_name: "Brandon",
    client_name: "Mom's Care Team",
    category: "messages" as const,
    action_type: "sent messages",
    description: "3 new messages in Mom's Care Team",
    timestamp: "3 hours ago",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "7",
    user_name: "Dr. Johnson",
    client_name: "Mary Johnson",
    category: "appointments" as const,
    action_type: "scheduled",
    description: "Appointment scheduled with Dr. Johnson",
    timestamp: "Today at 2:15 PM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "8",
    user_name: "Sarah",
    client_name: "Robert Chen",
    category: "medical" as const,
    action_type: "updated face sheet",
    description: "Sarah updated face sheet",
    timestamp: "Yesterday at 4:30 PM",
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Dashboard specific dummy data
const today = new Date();
today.setHours(0, 0, 0, 0);

export const DASHBOARD_TODAYS_APPOINTMENTS = [
  {
    id: "dashboard-appt-1",
    client_id: "1",
    createdBy: DASHBOARD_DUMMY_USER,
    title: "Cardiology Appointment",
    appointment_type: "cardiology",
    provider_id: "1",
    location: "Main Medical Center - Room 205",
    start_time: new Date(today.getTime() + 9 * 60 * 60 * 1000).toISOString(), // 9:00 AM
    end_time: new Date(today.getTime() + 10 * 60 * 60 * 1000).toISOString(), // 10:00 AM
    all_day: false,
    notes: "Follow-up appointment",
    reminder_sent: true,
    active: true,
    created_by: "1",
    healthcare_provider_id: "1",
    createdAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(today.getTime() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "dashboard-appt-2",
    client_id: "2",
    createdBy: DASHBOARD_DUMMY_USER,
    title: "Physical Therapy Session",
    appointment_type: "physical_therapy",
    provider_id: "2",
    location: "Rehabilitation Center",
    start_time: new Date(today.getTime() + 14 * 60 * 60 * 1000).toISOString(), // 2:00 PM
    end_time: new Date(today.getTime() + 15 * 60 * 60 * 1000).toISOString(), // 3:00 PM
    all_day: false,
    notes: "Knee rehabilitation",
    reminder_sent: false,
    active: true,
    created_by: "1",
    healthcare_provider_id: "2",
    createdAt: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(today.getTime() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "dashboard-appt-3",
    client_id: "1",
    createdBy: DASHBOARD_DUMMY_USER,
    title: "Lab Work",
    appointment_type: "laboratory",
    provider_id: "1",
    location: "Medical Lab Services",
    start_time: new Date(today.getTime() + 11 * 60 * 60 * 1000).toISOString(), // 11:00 AM
    end_time: new Date(today.getTime() + 11 * 30 * 60 * 1000).toISOString(), // 11:30 AM
    all_day: false,
    notes: "Blood work and routine tests",
    reminder_sent: false,
    active: true,
    created_by: "1",
    healthcare_provider_id: "1",
    createdAt: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(today.getTime() - 3 * 24 * 60 * 60 * 1000),
  },
];

export const DASHBOARD_RECENT_MESSAGES = [
  {
    id: "dashboard-thread-1",
    primary_user_id: "1",
    user_id: "1",
    started_at: new Date(Date.now() - 5 * 60 * 1000), // 5 minutes ago
    last_message: "Updated medication schedule for next week",
    last_message_time: new Date(Date.now() - 5 * 60 * 1000),
    last_message_sender_id: "2",
    client_id: "1",
    type: "client" as const,
    created_by: "1",
    participants_ids: ["1", "2", "3"],
    has_unread_messages: true,
    unread_count: 2,
    name: "Mary's Care Team",
    participants: [],
    messages: [],
  },
  {
    id: "dashboard-thread-2",
    primary_user_id: "1",
    user_id: "2",
    started_at: new Date(Date.now() - 60 * 60 * 1000), // 1 hour ago
    last_message: "Question about tomorrow's appointment time",
    last_message_time: new Date(Date.now() - 60 * 60 * 1000),
    last_message_sender_id: "2",
    client_id: undefined,
    type: "general" as const,
    created_by: "1",
    participants_ids: ["1", "2"],
    has_unread_messages: true,
    unread_count: 1,
    name: undefined,
    participants: [],
    messages: [],
  },
];

export const DASHBOARD_CLIENT_STATS = {
  activeClients: 24,
  deactivatedClients: 7,
  upcomingAppointments: 12,
  unreadMessages: 8,
  recentDocuments: 5,
  todaysAppointments: 5,
};

export const DASHBOARD_QUICK_ACCESS_CLIENTS = [
  {
    id: "1",
    first_name: "Mary",
    last_name: "Johnson",
    date_of_birth: "1945-03-15",
    living_situation: "Home Care",
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "2",
    first_name: "Robert",
    last_name: "Chen",
    date_of_birth: "1952-07-20",
    living_situation: "Assisted Living",
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "3",
    first_name: "Cathy",
    last_name: "Shoemaker",
    date_of_birth: null,
    living_situation: "Independent Living",
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: "4",
    first_name: "Sarah",
    last_name: "Williams",
    date_of_birth: "1940-01-10",
    living_situation: "Nursing Home",
    active: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const DASHBOARD_RECENT_DOCUMENTS = [
  {
    id: "dashboard-doc-1",
    title: "Lab Results - Blood Work",
    category: "Medical Records",
    description: "Recent blood test results",
    document_type: "pdf",
    file_size: 1258291, // 1.2 MB
    file_type: "application/pdf",
    file_url: "https://example.com/lab-results.pdf",
    file_name: "lab_results_2025_10_19.pdf",
    s3_bucket: "documents",
    client_id: "1",
    active: true,
    upload_type: "client" as const,
    uploadedBy: DASHBOARD_DUMMY_USER,
    createdAt: new Date(Date.now() - 2 * 60 * 1000), // 2 minutes ago
    updatedAt: new Date(Date.now() - 2 * 60 * 1000),
  },
  {
    id: "dashboard-doc-2",
    title: "Medication Update",
    category: "Medical Records",
    description: "Updated medication list",
    document_type: "pdf",
    file_size: 524288, // 512 KB
    file_type: "application/pdf",
    file_url: "https://example.com/medication-update.pdf",
    file_name: "medication_update_2025_10_18.pdf",
    s3_bucket: "documents",
    client_id: "1",
    active: true,
    upload_type: "client" as const,
    uploadedBy: DASHBOARD_DUMMY_USER,
    createdAt: new Date(Date.now() - 1 * 60 * 60 * 1000), // 1 hour ago
    updatedAt: new Date(Date.now() - 1 * 60 * 60 * 1000),
  },
  {
    id: "dashboard-doc-3",
    title: "Insurance Document",
    category: "Legal Documents",
    description: "Updated insurance policy",
    document_type: "pdf",
    file_size: 1048576, // 1 MB
    file_type: "application/pdf",
    file_url: "https://example.com/insurance.pdf",
    file_name: "insurance_2025_10_17.pdf",
    s3_bucket: "documents",
    client_id: "2",
    active: true,
    upload_type: "client" as const,
    uploadedBy: DASHBOARD_DUMMY_USER,
    createdAt: new Date(Date.now() - 24 * 60 * 60 * 1000), // 1 day ago
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000),
  },
];
