import { APP_ACTIONS } from "./app_action";

export const PERMISSIONS = {
  admin: [
    APP_ACTIONS.BillingPage,
    APP_ACTIONS.EditClientBasicInfo,
    APP_ACTIONS.EditClientMedicalInfo,
    APP_ACTIONS.EditClientNotes,
    APP_ACTIONS.DeleteDocs,
    APP_ACTIONS.AddClient,
    APP_ACTIONS.AccessControl,
    APP_ACTIONS.ClientAppointmentInfoEdit,
    APP_ACTIONS.ChangeClientStatus,
    APP_ACTIONS.AddDocs,
    APP_ACTIONS.ClientAppointmentAdd,
    APP_ACTIONS.EditAgensyForms,
    APP_ACTIONS.ViewPersonalInfo,
    APP_ACTIONS.OCRAccess,
    APP_ACTIONS.ClientContactAccess,
  ],
  primary_user: [
    APP_ACTIONS.BillingPage,
    APP_ACTIONS.ClientContactAccess,
    APP_ACTIONS.EditClientBasicInfo,
    APP_ACTIONS.EditClientMedicalInfo,
    APP_ACTIONS.EditClientNotes,
    APP_ACTIONS.DeleteDocs,
    APP_ACTIONS.AddClient,
    APP_ACTIONS.AccessControl,
    APP_ACTIONS.ClientAppointmentInfoEdit,
    APP_ACTIONS.ChangeClientStatus,
    APP_ACTIONS.AddDocs,
    APP_ACTIONS.ClientAppointmentAdd,
    APP_ACTIONS.EditAgensyForms,
    APP_ACTIONS.ViewPersonalInfo,
    APP_ACTIONS.OCRAccess,
  ],
  caregiver: [
    APP_ACTIONS.OCRAccess,
    APP_ACTIONS.EditClientBasicInfo,
    APP_ACTIONS.EditClientNotes,
    APP_ACTIONS.AddDocs,
    APP_ACTIONS.EditClientMedicalInfo,
    APP_ACTIONS.ClientAppointmentInfoEdit,
    APP_ACTIONS.ClientAppointmentAdd,
    APP_ACTIONS.EditAgensyForms,
  ],
  family_member: [APP_ACTIONS.AddDocs],
};
