import type { ChecklistField } from "@agensy/types";

export const carePlanChecklistSchema: ChecklistField[] = [
  {
    id: "0",
    type: "heading",
    label:
      "A CARE PLAN MEETING IS AN IMPORTANT PROCESS THAT EVALUATES THE FOLLOWING INFORMATION",
    parentId: null,
    headingId: "0",
  },
  {
    id: "1",
    type: "group",
    label: "The current care and services being received.",
    parentId: null,
    headingId: "0",
  },
  {
    id: "2",
    type: "group",
    label: "Identifying any problems or issues or safety concerns.",
    parentId: null,
    headingId: "0",
  },
  {
    id: "3",
    type: "group",
    label: "Determining the appropriate treatment or next steps.",
    parentId: null,
    headingId: "0",
  },
  {
    id: "4",
    type: "heading",
    label: "CARE PLAN MEETINGS ARE MOST OFTEN CALLED WHEN",
    parentId: null,
    headingId: "4",
  },
  {
    id: "5",
    type: "group",
    label:
      "Your loved one moves to a higher level of care (home to assisted living, assisted living to memory care, etc.)",
    parentId: null,
    headingId: "4",
  },
  {
    id: "6",
    type: "group",
    label: "After a hospitalization.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "7",
    type: "group",
    label: "After admission to a skilled nursing or rehab facility.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "8",
    type: "group",
    label: "Prior to discharge from skilled nursing or rehab.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "9",
    type: "group",
    label: "Every six months or annually depending on the need.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "10",
    type: "group",
    label: "If there is an illness or acute change in condition.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "11",
    type: "group",
    label: "After receiving a new diagnosis.",
    parentId: null,
    headingId: "4",
  },
  {
    id: "12",
    type: "heading",
    label: "SKILLED NURSING",
    parentId: null,
    headingId: "12",
  },
  {
    id: "13",
    type: "group",
    label: "Schedule a Care Plan within two days of admission.",
    parentId: null,
    headingId: "12",
  },
  {
    id: "13.1",
    type: "checkbox",
    label: "Request the following professionals attend the meeting:",
    parentId: "13",
    headingId: "12",
  },
  {
    id: "13.1.1",
    type: "radio",
    options: [
      "Nursing staff",
      "Dietary staff",
      "Activities coordinator",
      "Physical / Occupational / Speech Therapy",
      "Social Worker",
      "Any other providers involved in care",
    ],
    label: "",
    parentId: "13.1",
    headingId: "12",
  },
  {
    id: "13.1.1.1",
    type: "radio",
    options: [
      "If the provider is unable to attend, request that they provide information about their assessment and treatment plan so it can be reported out to the group during the meeting",
    ],
    label: "",
    parentId: "13.1.1",
    headingId: "12",
    parentOption: "Any other providers involved in care",
  },
  {
    id: "13.2",
    type: "checkbox",
    label: "Request a hard copy of the care plan",
    parentId: "13",
    headingId: "12",
  },
  {
    id: "13.3",
    type: "checkbox",
    label: "Review the following:",
    parentId: "13",
    headingId: "12",
  },
  {
    id: "13.3.1",
    type: "radio",
    options: [
      "Current Diagnoses",
      "Goals for Treatment",
      "Anticipated Length of Stay",
      "Medications that client admitted with and any medication changes",
      "Therapies received and frequency of treatment",
      "Specialty care (wound care, psych, etc.)",
      "What level of care is staff recommending patient discharge with",
      "Who to contact for updates",
    ],
    label: "",
    parentId: "13.3",
    headingId: "12",
  },
  {
    id: "13.3.1.1",
    type: "radio",
    options: [
      "Assisted Living, Memory Care, Home with caregiver support, Independent Living / Home.",
    ],
    label: "",
    parentId: "13.3.1",
    headingId: "12",
    parentOption:
      "What level of care is staff recommending patient discharge with",
  },
  {
    id: "14",
    type: "group",
    label:
      "Schedule a care plan every 14 days if care recipient has extended admission.",
    parentId: null,
    headingId: "12",
  },

  {
    id: "15",
    type: "group",
    label: "Schedule a care plan 2 days prior to discharge.",
    parentId: null,
    headingId: "12",
  },
  {
    id: "15.1",
    type: "checkbox",
    label: "Request the following professionals attend the meeting:",
    parentId: "15",
    headingId: "12",
  },
  {
    id: "15.1.1",
    type: "radio",
    options: [
      "Nursing staff",
      "Dietary staff",
      "Activities coordinator",
      "Physical / Occupational / Speech Therapy",
      "Social Worker",
      "Any other providers involved in care",
    ],
    label: "",
    parentId: "15.1",
    headingId: "12",
  },
  {
    id: "15.1.1.1",
    type: "radio",
    options: [
      "If the provider is unable to attend, request that they provide information about their assessment and treatment plan so it can be reported out to the group during the meeting.",
    ],
    label: "",
    parentId: "15.1.1",
    headingId: "12",
    parentOption: "Any other providers involved in care",
  },
  {
    id: "15.2",
    type: "checkbox",
    label: "Review the following:",
    parentId: "15",
    headingId: "12",
  },
  {
    id: "15.2.1",
    type: "radio",
    options: [
      "Current Diagnoses",
      "Medication changes that happened during skilled nursing stay",
      "Medications that patient is being discharged home with",
      "Is patient being discharged with home health (nursing, physical / occupational / speech therapy)",
      "Is patient being discharged with any new durable medical equipment",
      "What level of care is staff recommending patient discharge with",
      "What follow up appointments need to be scheduled",
    ],
    label: "",
    parentId: "15.2",
    headingId: "12",
  },
  {
    id: "15.2.1.1",
    type: "radio",
    options: ["Wheelchair, walker, oxygen."],
    label: "",
    parentId: "15.2.1",
    headingId: "12",
    parentOption:
      "Is patient being discharged with any new durable medical equipment",
  },
  {
    id: "15.2.1.1",
    type: "radio",
    options: [
      "Assisted Living, Memory Care, Home with caregiver support, Independent Living / Home.",
    ],
    label: "",
    parentId: "15.2.1",
    headingId: "12",
    parentOption:
      "What level of care is staff recommending patient discharge with",
  },
  {
    id: "16",
    type: "heading",
    label: "ASSISTED LIVING OR MEMORY CARE",
    parentId: null,
    headingId: "16",
  },
  {
    id: "17",
    type: "group",
    label: "Schedule a Care Plan within one week of admission",
    parentId: null,
    headingId: "16",
  },
  {
    id: "17.1",
    type: "checkbox",
    label:
      "Care plans can be scheduled every six months, if there is a hospitalization or new diagnosis, or if there is an acute change in condition or behaviors / concerns that need to be addressed.",
    parentId: "17",
    headingId: "16",
  },
  {
    id: "17.1.1",
    type: "radio",
    options: [
      "Assisted Living or Memory Care Director",
      "Nursing staff that is involved in care",
      "Physical / Occupational / Speech Therapy",
    ],
    label: "",
    parentId: "17.1",
    headingId: "16",
  },
  {
    id: "17.2",
    type: "checkbox",
    label: "Review the following:",
    parentId: "17",
    headingId: "16",
  },
  {
    id: "17.2.1",
    type: "radio",
    options: [
      "Request a hard copy of the care plan from the community - review shower schedule, laundry / housekeeping days, hands on care provided by staff, medication administration schedule",
      "Discuss current diagnoses and treatment",
      "Review medication list and keep a copy for your records",
      "Discuss any therapies being received - physical / occupational / speech",
      "Review list of upcoming medical appointments",
    ],
    label: "",
    parentId: "17.2",
    headingId: "16",
  },
  {
    id: "17.2.1.1",
    type: "radio",
    options: [
      "Make sure community knows what specialty providers are being seen",
      "Discuss community rules / protocol for off site appointments",
      "Review transportation schedule (if offered by the community) and how to book transportation requests.",
    ],
    label: "",
    parentId: "17.2.1",
    headingId: "16",
    parentOption: "Review list of upcoming medical appointments",
  },
  {
    id: "17.2.1.1.1",
    type: "radio",
    options: [
      "Bring a copy of the medical appointment template",
      "Make sure you understand how to relay medication changes back to community",
    ],
    label: "",
    parentId: "17.2.1.1",
    headingId: "16",
    parentOption:
      "Discuss community rules / protocol for off site appointments",
  },
  {
    id: "17.2.1.1.1.1",
    type: "radio",
    options: [
      "Do you need a hard copy prescription?",
      "Where do you send orders for medication changes?",
    ],
    label: "",
    parentId: "17.2.1.1.1",
    headingId: "16",
    parentOption:
      "Make sure you understand how to relay medication changes back to community",
  },
  {
    id: "18",
    type: "heading",
    label: "IN ASSISTED LIVING OR MEMORY CARE",
    parentId: null,
    headingId: "18",
  },
  {
    id: "19",
    type: "group",
    label: "Schedule a Care Plan within first few days of admission.",
    parentId: null,
    headingId: "18",
  },
  {
    id: "20",
    type: "group",
    label:
      "Schedule Care Plans every six months, or if the client has an acute change in condition or behaviors that need to be addressed.",
    parentId: null,
    headingId: "18",
  },
  {
    id: "21",
    type: "group",
    label: "Review Medication list and update in Care Tree.",
    parentId: null,
    headingId: "18",
  },
  {
    id: "22",
    type: "group",
    label:
      "Review any likes / dislikes or anticipated concerns that Agensy staff has.",
    parentId: null,
    headingId: "18",
  },
  {
    id: "23",
    type: "group",
    label: "If Care Plan is for change in condition:",
    parentId: null,
    headingId: "18",
  },
  {
    id: "23.1",
    type: "checkbox",
    label: "Review treatment plan.",
    parentId: "23",
    headingId: "18",
  },
  {
    id: "23.2",
    type: "checkbox",
    label: "Review emergency plan.",
    parentId: "23",
    headingId: "18",
  },
  {
    id: "23.3",
    type: "checkbox",
    label: "Document providers involved.",
    parentId: "23",
    headingId: "18",
  },
  {
    id: "23.4",
    type: "checkbox",
    label: "Review medication changes by all providers.",
    parentId: "23",
    headingId: "18",
  },
  {
    id: "23.5",
    type: "checkbox",
    label: "Review any specialty providers client is seeing.",
    parentId: "23",
    headingId: "18",
  },
  {
    id: "24",
    type: "group",
    label: "If Care Plan is to address behavioral concerns:",
    parentId: null,
    headingId: "18",
  },
  {
    id: "24.1",
    type: "checkbox",
    label: "Discuss any steps taken to alleviate behaviors.",
    parentId: "24",
    headingId: "18",
  },
  {
    id: "24.2",
    type: "checkbox",
    label: "Discuss appropriate medication changes.",
    parentId: "24",
    headingId: "18",
  },
  {
    id: "24.3",
    type: "checkbox",
    label:
      "Discuss environmental changes that can be made to alleviate behaviors.",
    parentId: "24",
    headingId: "18",
  },
  {
    id: "25",
    type: "group",
    label: "If Care Plan is for a general update.",
    parentId: null,
    headingId: "18",
  },
  {
    id: "25.1",
    type: "checkbox",
    label: "Review medication list.",
    parentId: "25",
    headingId: "18",
  },
  {
    id: "25.2",
    type: "checkbox",
    label:
      "Ensure all information on Face Sheet (Community and Agensy) is correct.",
    parentId: "25",
    headingId: "18",
  },
  {
    id: "25.3",
    type: "checkbox",
    label: "Confirm code status.",
    parentId: "25",
    headingId: "18",
  },
  {
    id: "25.4",
    type: "checkbox",
    label: "Update list of preferred providers.",
    parentId: "25",
    headingId: "18",
  },
  {
    id: "25.5",
    type: "checkbox",
    label: "Confirm community has all needed documents - MPOA, DNR, etc.",
    parentId: "25",
    headingId: "18",
  },
  {
    id: "26",
    type: "heading",
    label: "HOME / INDEPENDENT LIVING",
    parentId: null,
    headingId: "26",
  },
  {
    id: "27",
    type: "group",
    label: "Use sample care plan document and face sheet to create care plan.",
    parentId: null,
    headingId: "26",
  },
  {
    id: "28",
    type: "group",
    label:
      "Review the care plan every six months or if there is a hospitalization, change in condition or new diagnosis.",
    parentId: null,
    headingId: "26",
  },
  {
    id: "28.1",
    type: "checkbox",
    label:
      "Review list of medical providers and any upcoming appointments, or appointments that need to be scheduled.",
    parentId: "28",
    headingId: "26",
  },
  {
    id: "28.2",
    type: "checkbox",
    label: "Update list of providers and contact information on face sheet.",
    parentId: "28",
    headingId: "26",
  },
  {
    id: "28.2.1",
    type: "radio",
    label: "",
    options: [
      "Home Health providers, in home caregivers, medical providers, emergency contacts, preferred pharmacy, preferred hospital.",
    ],
    parentId: "28.2",
    headingId: "26",
  },
  {
    id: "28.3",
    type: "checkbox",
    label: "Identify potential safety concerns.",
    parentId: "28",
    headingId: "26",
  },
  {
    id: "28.3.1",
    type: "radio",
    label: "",
    options: [
      "In home safety",
      "Driving safety",
      "Medication administration",
      "1:1 care needs",
    ],
    parentId: "28.3",
    headingId: "26",
  },
  {
    id: "29",
    type: "group",
    label:
      "Consider future needs and identify resources for long term care planning.",
    parentId: null,
    headingId: "26",
  },
  {
    id: "30",
    type: "heading",
    label: "IF CARE PLAN IS FOR CHANGE IN HEALTH CONDITION",
    parentId: null,
    headingId: "30",
  },
  {
    id: "31",
    type: "group",
    label: "Document symptoms",
    parentId: null,
    headingId: "30",
  },
  {
    id: "31.1",
    type: "checkbox",
    label: "Severity",
    parentId: "31",
    headingId: "30",
  },
  {
    id: "31.2",
    type: "checkbox",
    label: "Frequency",
    parentId: "31",
    headingId: "30",
  },

  {
    id: "32",
    type: "group",
    label: "Document symptoms",
    parentId: null,
    headingId: "30",
  },
  {
    id: "32.1",
    type: "checkbox",
    label: "Which medical providers are involved",
    parentId: "32",
    headingId: "30",
  },
  {
    id: "32.2",
    type: "checkbox",
    label: "Upcoming appointments are scheduled",
    parentId: "32",
    headingId: "30",
  },
  {
    id: "32.2.1",
    type: "radio",
    options: ["Primary Care, Specialty Providers, Imaging, Labs, Tests"],
    label: "",
    parentId: "32.2",
    headingId: "30",
  },
  {
    id: "32.3",
    type: "checkbox",
    label: "Any medication changes",
    parentId: "32",
    headingId: "30",
  },
  {
    id: "33",
    type: "group",
    label: "Discuss any medication changes",
    parentId: null,
    headingId: "30",
  },
  {
    id: "34",
    type: "group",
    label: "Review emergency plan",
    parentId: null,
    headingId: "30",
  },
  {
    id: "34.1",
    type: "checkbox",
    label: "Preferred hospital",
    parentId: "34",
    headingId: "30",
  },
  {
    id: "34.2",
    type: "checkbox",
    label: "Emergency contact",
    parentId: "34",
    headingId: "30",
  },
  {
    id: "34.3",
    type: "checkbox",
    label: "Preferred hospital",
    parentId: "34",
    headingId: "30",
  },
  {
    id: "35",
    type: "heading",
    label: "IF CARE PLAN IS TO ADDRESS BEHAVIORAL CONCERNS:",
    parentId: null,
    headingId: "35",
  },
  {
    id: "36",
    type: "group",
    label: "When did behaviors begin",
    parentId: null,
    headingId: "35",
  },
  {
    id: "36.1",
    type: "checkbox",
    label: "Document onset, frequency, severity",
    parentId: "36",
    headingId: "35",
  },
  {
    id: "36.2",
    type: "checkbox",
    label: "Is there a medical reason behind behavior that can be addressed",
    parentId: "36",
    headingId: "35",
  },
  {
    id: "37",
    type: "group",
    label: "Discuss appropriate medication changes",
    parentId: null,
    headingId: "35",
  },
  {
    id: "38",
    type: "group",
    label: "Notify medical providers of behavior changes and concerns",
    parentId: null,
    headingId: "35",
  },
  {
    id: "39",
    type: "group",
    label:
      "Discuss environmental changes that can be made to alleviate behaviors",
    parentId: null,
    headingId: "35",
  },
  {
    id: "40",
    type: "group",
    label:
      "Identify safety concerns and steps being taken to address behaviors",
    parentId: null,
    headingId: "35",
  },
  {
    id: "41",
    type: "heading",
    label: "IF CARE PLAN IS FOR A GENERAL UPDATE",
    parentId: null,
    headingId: "41",
  },
  {
    id: "42",
    type: "group",
    label: "Review medication list",
    parentId: null,
    headingId: "41",
  },
  {
    id: "43",
    type: "group",
    label: "Confirm all information on Face Sheet is correct",
    parentId: null,
    headingId: "41",
  },
  {
    id: "44",
    type: "group",
    label: "Update emergency contact list",
    parentId: null,
    headingId: "41",
  },
  {
    id: "45",
    type: "group",
    label: "Confirm code status",
    parentId: null,
    headingId: "41",
  },
  {
    id: "45.1",
    type: "checkbox",
    label: "Full Code vs. Do Not Resuscitate",
    parentId: "45",
    headingId: "41",
  },
  {
    id: "46",
    type: "group",
    label: "Update list of providers",
    parentId: null,
    headingId: "41",
  },
  {
    id: "46.1",
    type: "checkbox",
    label: "Primary Care",
    parentId: "46",
    headingId: "41",
  },
  {
    id: "46.2",
    type: "checkbox",
    label: "Specialty Providers",
    parentId: "46",
    headingId: "41",
  },
  {
    id: "46.3",
    type: "checkbox",
    label: "Home Health",
    parentId: "46",
    headingId: "41",
  },
  {
    id: "46.4",
    type: "checkbox",
    label: "In Home Care",
    parentId: "46",
    headingId: "41",
  },
];

export const generateCarePlanChecklistDefaultValues = (): Record<
  string,
  boolean | null
> => {
  const defaultValues: Record<string, boolean | null> = {};

  carePlanChecklistSchema.forEach((field) => {
    if (field.type === "checkbox") {
      defaultValues[field.id] = false;
    } else if (field.type === "radio") {
      defaultValues[field.id] = null;
    }
  });

  return defaultValues;
};
